---
# tasks file for upgrade_packages
- name: update_packages | Update all packages RedHat
  yum:
    name: "{{ update_packages_name }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: update_packages | Update all packages Debian
  apt:
    name: "{{ update_packages_name }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
